services:
  - type: web
    name: mini-crm-future-fs
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: JWT_SECRET
        value: supersecret_crm_key_123
      - key: PORT
        value: 5000
